spring:
    profiles:
    active:
        -dev
            
---
spring:
    profiles: dev
    application:
        name: microservice_dev
            
---
spring:
    profiles: test
    application:
        name: microservice_test